cloud:
  aws:
    credentials:
      access-key: AKIA4WB3FIPOM2JPSZQH 
      secret-key: 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
    region:
      static: us-west-2
    stack:
      auto: false

application:
  bucket:
    name: spring-boot-project-storage

server:
  port: 9000
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
      
spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@127.0.0.1:1521:orcl11
    username: scott
    password: tiger
      
  jpa:
    hibernate:
      ddl-auto: update #create update none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
          
